<?php

/**
 * @file
 * Contains od_ext_fonts.module.
 */

/**
 * Implements hook_library_info_build().
 */
function od_ext_fonts_library_info_build() {
  $libraries = [];

  $libraries['opengov'] = [
    'css' => [
      'base' => [
        '/' . drupal_get_path('profile', 'od') . '/libraries/opengov/app/assets/stylesheets/fontopengov.css' => [],
      ],
    ],
  ];

  return $libraries;
}

/**
 * Implements hook_page_attachments().
 */
function od_ext_fonts_page_attachments(array &$page) {
  // Don't add the JavaScript and CSS during installation.
  if (drupal_installation_attempted()) {
    return;
  }

  $page['#attached']['library'][] = 'od_ext_fonts/opengov';
}
