<?php

/**
 * @file
 * Contains od_solr_external.module.
 */

use Drupal\Core\Render\Markup;
use Drupal\search_api\Query\QueryInterface;
use Drupal\views\ViewExecutable;
use Solarium\QueryType\Select\Query\Query as SolariumQuery;

/**
 * Implements hook_search_api_solr_query_alter().
 */
function od_solr_external_search_api_solr_query_alter(SolariumQuery $solarium_query, QueryInterface $query) {
  // Do not alter the query if the index does not use the solr_document
  // datasource.
  $index = $query->getIndex();
  if (!$index->isValidDatasource('solr_document')) {
    return;
  }

  // Language handling.
  $language = Drupal::languageManager()->getCurrentLanguage();

  if ($index->id() == 'pd_core_ati') {
    $solarium_query->createFilterQuery('od_solr_external_language')->setQuery('ss_language:' . $language->getId());
  }

}

/**
 * Implements hook_views_pre_render().
 */
function od_solr_external_views_pre_render(ViewExecutable $view) {
  $language_manager = \Drupal::service('language_manager');
  $currentLang = $language_manager->getCurrentLanguage()->getId();
  $defaultLang = $language_manager->getDefaultLanguage()->getId();

  $cores = [
    'pd_core_ati' => ['block_1', 'block_2'],
    'pd_core_grants' => ['block_1', 'block_2'],
    'pd_core_contracts' => ['block_1', 'block_2'],
    'pd_core_hospitalityq' => ['block_1', 'block_2'],
    'pd_core_inventory' => ['block_1', 'block_2'],
    'pd_core_reclassification' => ['block_1', 'block_2'],
    'pd_core_travela' => ['block_1', 'block_2'],
    'pd_core_travelq' => ['block_1', 'block_2'],
    'pd_core_wrongdoing' => ['block_1', 'block_2'],
    'solr_inventory' => ['block_1'],
  ];

  foreach ($cores as $core => $coreDisplay) {

    if ($view->id() == $core &&  in_array($view->current_display, $coreDisplay)) {
      /** @var \Drupal\Core\Language\LanguageManagerInterface $language_manager */
      if ($defaultLang != $currentLang) {
        if (!empty($view->style_plugin->options['panel_title_field'])) {
          if ($core == 'solr_inventory' && $currentLang == 'fr') {
            $view->style_plugin->options['panel_title_field'] = str_replace('title', 'field_title_fr', $view->style_plugin->options['panel_title_field']);
          }
          else {
            $view->style_plugin->options['panel_title_field'] = str_replace('_' . $defaultLang, '_' . $currentLang, $view->style_plugin->options['panel_title_field']);
          }
        }
      }
      foreach ($view->field as $field) {
        if ($defaultLang != $currentLang) {
          if (strpos($field->field, '_' . $defaultLang) !== FALSE) {
            unset($view->field[$field->field]);
          }
        }
        else {
          if (strpos($field->field, '_fr') !== FALSE) {
            unset($view->field[$field->field]);
          }
        }
      }
    }
  }

  if ($view->id() == 'solr_search_content') {
    if (!empty($view->exposed_widgets['#action']) && $view->current_display === 'solr_app') {
      $view->exposed_widgets['#action'] = '/' . $currentLang . '/apps/';
      $view->exposed_widgets['search_api_fulltext']['#attributes'] = [
        'placeholder' => t('Search...'),
      ];
    }
  }

}

/**
 * Implements hook_preprocess_views_view_fields().
 */
function od_solr_external_preprocess_views_view_fields(&$variables) {
  $view = $variables['view'];

  // Grab titles (en + fr) from data_dict in json response.
  if ($view->id() == 'ext_core_ckan' && $view->current_display == 'block_1' ||
      $view->id() == 'ext_core_ckan' && $view->current_display == 'block_3') {
    $language = Drupal::languageManager()->getCurrentLanguage();
    $id = $variables['fields']['id']->content->__toString();
    $str = $variables['fields']['nothing']->content->__toString();
    $str = html_entity_decode($str);
    $str = json_decode($str, TRUE);
    if ($language->getId() == 'fr') {
      $str = Markup::Create('<a href="' . \Drupal::request()->getSchemeAndHttpHost() . '/' . $language->getId() . '/data/' . $language->getId() . '/dataset/' . $id . '">' . $str['fr'] . '</a>');
    }
    else {
      $str = Markup::Create('<a href="' . \Drupal::request()->getSchemeAndHttpHost() . '/' . $language->getId() . '/data/' . $language->getId() . '/dataset/' . $id . '">' . $str['en'] . '</a>');
    }
    unset($variables['fields']['id']);
    $variables['fields']['nothing']->content = $str;

    if ($view->current_display == 'block_3') {
      $str = $variables['fields']['nothing_1']->content->__toString();
      $str = html_entity_decode($str);
      $str = json_decode($str, TRUE);
      if ($language->getId() == 'fr') {
        $variables['fields']['nothing_1']->content = $str['fr'];
      }
      else {
        $variables['fields']['nothing_1']->content = $str['en'];
      }
    }
  }
}
