<?php

/**
 * @file
 * Contains od_core.module.
 */

use Drupal\Core\Database\Database;
use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\QueryPluginBase;

/**
 * Implements hook_views_query_alter().
 */
function od_core_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {

  $db = Database::getConnection()->driver();
  if ($db == 'pgsql') {
    // TODO: Drupal core should be handling this.
    if (!empty($view->relationship['entityqueue_relationship'])) {
      $query->getTableInfo('entity_subqueue__items')['join']->field .= '::bigint';
    }
    if (!empty($view->relationship['flag_relationship'])) {
      $query->getTableInfo('flagging_node_field_data')['join']->field .= '::bigint';
    }
  }
}

/**
 * Implements hook_token_info().
 */
function od_core_token_info() {
  $info['tokens']['site']['url-abs'] = [
    'name' => t('Absolute URL'),
    'description' => t('Url of the site, no language prefix garanted'),
  ];
  return $info;
}

/**
 * Implements hook_tokens().
 */
function od_core_tokens($type, $tokens, array $data = [], array $options = []) {
  $replacements = [];
  global $base_root;

  if ($type == 'site') {

    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'url-abs':
          $replacements[$original] = $base_root;
          break;
      }
    }
  }

  return $replacements;
}
